### ISSUE TITLE
Mobile Compatability.

### ISSUE THREAD

**Issue by Tytan-Codes-Alt** [AmreshSinha/wink#4]
TITLE. Can you make it compatible on mobile.

**Comment by AmreshSinha** [comment]
> TITLE. Can you make it compatible on mobile.

Ahh.. sorry for the late reply. And Happy New Year!
I think it is responsive enough for mobile screens.

Can you send screenshots of the issues or responsive bugs you have discovered (also do tell me the screen dimensions or device model)?
